"""create initial tables

Revision ID: 038f1f9ff5b7
Revises:
Create Date: 2026-03-24 19:24:06.925433

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parents[1]))

from helpers import drop_enum

# revision identifiers, used by Alembic.
revision = "038f1f9ff5b7"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lessons",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("s3_key", sa.String(), nullable=True),
        sa.Column(
            "lesson_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "modules",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("s3_key", sa.String(), nullable=True),
        sa.Column(
            "module_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "question_generator_groups",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "generator_type",
            sa.Enum("GENERAL", "WORD", "WORD_PAIRING", name="generator-type"),
            nullable=False,
        ),
        sa.Column("name", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "subjects",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("s3_key", sa.String(), nullable=True),
        sa.Column(
            "subject_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("anonymous_id", sa.UUID(), nullable=True),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("hashed_salted_password", sa.String(), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "STUDENT", "TEACHER", "PARENT", "LOCAL_ADMIN", "ADMIN", name="role"
            ),
            nullable=False,
        ),
        sa.Column("display_name", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("user_source", sa.String(), nullable=True),
        sa.Column("gdpr_consent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "data_deletion_requested_at", sa.DateTime(timezone=True), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "interactions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("anonymous_id", sa.UUID(), nullable=False),
        sa.Column("event_type", sa.String(), nullable=False),
        sa.Column("event_category", sa.String(), nullable=True),
        sa.Column("page_url", sa.String(), nullable=True),
        sa.Column("page_path", sa.String(), nullable=True),
        sa.Column("referrer_url", sa.String(), nullable=True),
        sa.Column("properties", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("ip_address", postgresql.INET(), nullable=True),
        sa.Column("user_agent", sa.String(), nullable=True),
        sa.Column("device_type", sa.String(), nullable=True),
        sa.Column("browser", sa.String(), nullable=True),
        sa.Column("os", sa.String(), nullable=True),
        sa.Column("screen_width", sa.Integer(), nullable=True),
        sa.Column("screen_height", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("client_ts", sa.DateTime(timezone=True), nullable=True),
        sa.Column("server_ts", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_user_session", "interactions", ["user_id", "session_id"], unique=False
    )
    op.create_table(
        "module_lessons",
        sa.Column("module_id", sa.UUID(), nullable=False),
        sa.Column("lesson_id", sa.UUID(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["lesson_id"],
            ["lessons.id"],
        ),
        sa.ForeignKeyConstraint(
            ["module_id"],
            ["modules.id"],
        ),
        sa.PrimaryKeyConstraint("module_id", "lesson_id"),
    )
    op.create_table(
        "progress",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("lesson_id", sa.UUID(), nullable=False),
        sa.Column("level", sa.Integer(), nullable=True),
        sa.Column("level_progress", sa.Integer(), nullable=True),
        sa.Column("answered_questions", sa.Integer(), nullable=True),
        sa.Column("questions_correct", sa.Integer(), nullable=True),
        sa.Column("questions_incorrect", sa.Integer(), nullable=True),
        sa.Column(
            "understanding_metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["lesson_id"],
            ["lessons.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_lesson", "progress", ["lesson_id"], unique=False)
    op.create_index(
        "idx_user_lesson", "progress", ["user_id", "lesson_id"], unique=False
    )
    op.create_table(
        "question_predefined_values",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("generator_group_id", sa.UUID(), nullable=False),
        sa.Column("value", sa.String(), nullable=True),
        sa.Column("pair_index", sa.Integer(), nullable=True),
        sa.Column("pair_order", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["generator_group_id"],
            ["question_generator_groups.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_generator_group_pair_index",
        "question_predefined_values",
        ["generator_group_id", "pair_index"],
        unique=False,
    )
    op.create_table(
        "questions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("lesson_id", sa.UUID(), nullable=False),
        sa.Column(
            "difficulty",
            sa.Enum("EASY", "NORMAL", "HARD", "CHALLENGE", name="difficulty"),
            nullable=False,
        ),
        sa.Column("template", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("times_encountered", sa.Integer(), nullable=True),
        sa.Column("times_correct", sa.Integer(), nullable=True),
        sa.Column("generator_group_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["generator_group_id"],
            ["question_generator_groups.id"],
        ),
        sa.ForeignKeyConstraint(
            ["lesson_id"],
            ["lessons.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "lesson_id"),
    )
    op.create_index(
        "idx_lesson_difficulty", "questions", ["lesson_id", "difficulty"], unique=False
    )
    op.create_table(
        "subject_modules",
        sa.Column("subject_id", sa.UUID(), nullable=False),
        sa.Column("module_id", sa.UUID(), nullable=False),
        sa.Column("order", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["module_id"],
            ["modules.id"],
        ),
        sa.ForeignKeyConstraint(
            ["subject_id"],
            ["subjects.id"],
        ),
        sa.PrimaryKeyConstraint("subject_id", "module_id"),
    )
    op.create_table(
        "subscriptions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("INACTIVE", "ACTIVE", name="subscription-status"),
            nullable=False,
        ),
        sa.Column(
            "billing_frequency",
            sa.Enum("MONTHLY", "YEARLY", name="billing-frequency"),
            nullable=False,
        ),
        sa.Column("current_period_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("current_period_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("recurring", sa.Boolean(), nullable=False),
        sa.Column(
            "start_day",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("cancel_day", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancel_reason", sa.String(), nullable=True),
        sa.Column(
            "cancel_enum_reason",
            sa.Enum("UNSPECIFIED", name="cancel-reason"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_user_id", "subscriptions", ["user_id"], unique=False)
    op.create_table(
        "payments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("subscription_id", sa.UUID(), nullable=True),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("amount_cents", sa.Integer(), nullable=False),
        sa.Column("period_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("period_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("failure_reason", sa.Text(), nullable=True),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("provider_payment_id", sa.String(length=255), nullable=True),
        sa.Column("provider_invoice_id", sa.String(length=255), nullable=True),
        sa.Column("invoice_url", sa.Text(), nullable=True),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("next_retry_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["subscription_id"],
            ["subscriptions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider_invoice_id"),
        sa.UniqueConstraint("provider_payment_id"),
    )
    op.create_index(
        "ix_payments_subscription_id", "payments", ["subscription_id"], unique=False
    )
    op.create_index("ix_payments_user_id", "payments", ["user_id"], unique=False)
    op.create_table(
        "question_history",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("question_id", sa.UUID(), nullable=False),
        sa.Column("lesson_id", sa.UUID(), nullable=False),
        sa.Column(
            "question_terms", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "question_answer", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "user_answer", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("correct", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["lesson_id"],
            ["lessons.id"],
        ),
        sa.ForeignKeyConstraint(
            ["question_id", "lesson_id"],
            ["questions.id", "questions.lesson_id"],
        ),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["questions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_history_user_lesson",
        "question_history",
        ["user_id", "lesson_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_history_user_lesson", table_name="question_history")
    op.drop_table("question_history")
    op.drop_index("ix_payments_user_id", table_name="payments")
    op.drop_index("ix_payments_subscription_id", table_name="payments")
    op.drop_table("payments")
    op.drop_index("idx_user_id", table_name="subscriptions")
    op.drop_table("subscriptions")
    op.drop_table("subject_modules")
    op.drop_index("idx_lesson_difficulty", table_name="questions")
    op.drop_table("questions")
    op.drop_index(
        "idx_generator_group_pair_index", table_name="question_predefined_values"
    )
    op.drop_table("question_predefined_values")
    op.drop_index("idx_user_lesson", table_name="progress")
    op.drop_index("idx_lesson", table_name="progress")
    op.drop_table("progress")
    op.drop_table("module_lessons")
    op.drop_index("idx_user_session", table_name="interactions")
    op.drop_table("interactions")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_table("subjects")
    op.drop_table("question_generator_groups")
    op.drop_table("modules")
    op.drop_table("lessons")
    drop_enum("generator-type")
    drop_enum("role")
    drop_enum("subscription-status")
    drop_enum("difficulty")
    drop_enum("billing-frequency")
    drop_enum("cancel-reason")
    # ### end Alembic commands ###
