"""adjusted progress and added index

Revision ID: 73687d0cbfb2
Revises: 9b77e5954eab
Create Date: 2026-04-28 22:06:28.744829

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "73687d0cbfb2"
down_revision = "9b77e5954eab"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "progress", sa.Column("created_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.create_index(
        "idx_user_updated_at", "progress", ["user_id", "updated_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_user_updated_at", table_name="progress")
    op.drop_column("progress", "created_at")
    # ### end Alembic commands ###
