"""updated question and progress to match api

Revision ID: 9b77e5954eab
Revises: b67ff2bed232
Create Date: 2026-04-12 01:50:25.244778

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parents[1]))

from helpers import create_enum

# revision identifiers, used by Alembic.
revision = "9b77e5954eab"
down_revision = "b67ff2bed232"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    create_enum("MULTIPLE_CHOICE", "TEXTBOX", name="question_style")
    op.add_column("progress", sa.Column("level_xp", sa.Integer(), nullable=True))
    op.add_column("progress", sa.Column("streak", sa.Integer(), nullable=True))
    op.drop_column("progress", "level_progress")
    op.add_column(
        "question_history",
        sa.Column(
            "question_values", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    op.add_column(
        "question_history",
        sa.Column(
            "question_choices", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    op.add_column(
        "question_history",
        sa.Column(
            "question_answers", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    op.drop_column("question_history", "question_answer")
    op.drop_column("question_history", "question_terms")
    op.add_column(
        "question_predefined_values",
        sa.Column("value_type", sa.String(), nullable=True),
    )
    op.add_column(
        "questions",
        sa.Column(
            "question_style",
            sa.Enum("MULTIPLE_CHOICE", "TEXTBOX", name="question_style"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("questions", "question_style")
    op.drop_column("question_predefined_values", "value_type")
    op.add_column(
        "question_history",
        sa.Column(
            "question_terms",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "question_history",
        sa.Column(
            "question_answer",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("question_history", "question_answers")
    op.drop_column("question_history", "question_choices")
    op.drop_column("question_history", "question_values")
    op.add_column(
        "progress",
        sa.Column("level_progress", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_column("progress", "streak")
    op.drop_column("progress", "level_xp")
    # ### end Alembic commands ###
