"""add_logic_for_pre_login_token

Revision ID: e47820caa7b9
Revises: 73687d0cbfb2
Create Date: 2026-05-19 22:34:02.804003

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e47820caa7b9"
down_revision = "73687d0cbfb2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("is_pre_login", sa.Boolean(), server_default="false", nullable=False),
    )
    op.alter_column("users", "email", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column(
        "users", "hashed_salted_password", existing_type=sa.VARCHAR(), nullable=True
    )
    op.create_check_constraint(
        "valid_user_state",
        "users",
        "\n            (is_pre_login = true AND email IS NULL AND hashed_salted_password IS NULL)\n            OR\n            (is_pre_login = false AND email IS NOT NULL AND hashed_salted_password IS NOT NULL)\n            ",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("valid_user_state", "users", type_="check")
    op.alter_column(
        "users", "hashed_salted_password", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column("users", "email", existing_type=sa.VARCHAR(), nullable=False)
    op.drop_column("users", "is_pre_login")
    # ### end Alembic commands ###
